### ISSUE TITLE
Cannot select portal through grid

### ISSUE THREAD

**Issue by dataspiller** [tehstone/IngressDronePath#2]
As long as grid is displayed, I cannot click on any portal under the grid.

Running latest versions of Chrome and Tampermonkey, script version is 0.8.1 - All other IITC plugins disabled.

**Comment by tehstone** [comment]
Can you verify that the merged change fixed this issue for you? I could not get a repro.

**Comment by dataspiller** [comment]
Yes this fixed the issue.
