### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by MatyiFKBT** [tehstone/IngressDronePath#5]
Hey,
I had installed the extension on my phone, and it works perfectly, but I can't get it to work on my desktop. It throws this error on line 274:
`ERROR: Execution of script 'IITC Plugin: Drone Travel Path Planner' failed! can't access lexical declaration 'settings' before initialization`
I also read #4 and disabled any other plugins that uses S2 cells, but still no luck.

**Comment by tehstone** [comment]
That's strange, you're the only one to report this. What device and browser are you using?

I just made an update that could potentially fix this issue so try removing and reinstalling the plugin now.

**Comment by MatyiFKBT** [comment]
Yup. Works now, didn't even had to reinstall.
