### ISSUE TITLE
Consider geodesic polylines.

### ISSUE THREAD

**Issue by azack** [tehstone/IngressDronePath#6]
Consider [L.geodesicPolyline](https://github.com/iitc-project/ingress-intel-total-conversion/blob/0fabfb68943fc833153d89454220fa638a8b9fb6/external/L.Geodesic.js#L126) over `L.polyLine` to draw the cells.  It may rarely matter at such a small cell size, though.

**Comment by tehstone** [comment]
The cells are never going to be large enough to matter for this plugin.
