### ISSUE TITLE
Alternative SVG icon - does not cover other information

### ISSUE THREAD

**Issue by Barthax** [tehstone/IngressDronePath#9]
A simple alteration to line 567 to invert the icon and make it transparent:

html: `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 159.12 145.78"><defs><style>.cls-1{fill:#000000;}</style></defs><title>dronenet-key</title><path class="cls-1" d="M103,91.75a40.09,40.09,0,0,0-10.58,37.76h-4.1a44.22,44.22,0,0,1,27.75-50.78l2,3.53A40,40,0,0,0,103,91.75Z"/><path class="cls-1" d="M114,102.71a24.56,24.56,0,0,0-5.27,26.8h-5.33A29.47,29.47,0,0,1,123.5,91.59l2.59,4.5A24.41,24.41,0,0,0,114,102.71Z"/><path class="cls-1" d="M71.88,120a43.25,43.25,0,0,1-1,9.48h-4.1a40,40,0,0,0-26.1-47.38l2-3.53A44,44,0,0,1,71.88,120Z"/><path class="cls-1" d="M57.38,120a28.87,28.87,0,0,1-1.57,9.48H50.47A24.51,24.51,0,0,0,32.67,96l2.62-4.52A29.49,29.49,0,0,1,57.38,120Z"/><path class="cls-1" d="M107.7,64.23a44,44,0,0,1-56.44-.42l2-3.54a40,40,0,0,0,52.37.43Z"/><path class="cls-1" d="M100.3,51.4a29.51,29.51,0,0,1-41.61-.48l2.62-4.54c.35.41.72.8,1.1,1.18a24.5,24.5,0,0,0,34.64,0h0c.22-.22.43-.44.64-.67Z"/><g id="Layer_3" data-name="Layer 3"><path class="cls-1" d="M142.26,120a11,11,0,1,1-11-11A11,11,0,0,1,142.26,120Z"/><path class="cls-1" d="M38.85,120a11,11,0,1,1-11-11A11,11,0,0,1,38.85,120Z"/><path class="cls-1" d="M90.7,30.25a11,11,0,1,1-11-11A11,11,0,0,1,90.7,30.25Z"/></g></svg>`,

**Comment by tehstone** [comment]
Added this marker along with a toggle in the settings to switch between this or the standard marker icon.
